/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Clear the entire cache for a directory. */
export declare function clearCache(root: string): void

/** Invalidate the cache for a specific file (e.g. on file delete). */
export declare function invalidateCache(root: string, filePath: string): void

/**
 * Scan a directory and return a JSON manifest string.
 * Uses caching — only re-parses files whose mtime has changed.
 */
export declare function scanDirectory(root: string): string

/**
 * Scan a single file and return a JSON array of manifest entries.
 * Used by the file watcher for incremental updates.
 */
export declare function scanFilePath(filePath: string): string

/** Get the Transit scanner version. */
export declare function version(): string
