/**
 * @sabeeirsharrma/codegen — Code generation from manifests
 *
 * Generates typed stubs and glue code from scanner manifests.
 * The primary output is transit.gen.ts — typed function wrappers
 * that provide type safety for cross-language calls.
 */

import type { Manifest, ManifestEntry } from "@sabeeirsharrma/schema";

// ─── TypeScript generation ──────────────────────────────────────────────────

export interface TypeScriptGenOptions {
  /** Output file path (default: "transit.gen.ts") */
  outputPath?: string;
  /** Whether to generate import statements (default: true) */
  generateImports?: boolean;
  /** Whether to generate the transit handle setup (default: true) */
  generateSetup?: boolean;
  /** Custom type mappings: function name → { params, returnType } */
  typeOverrides?: Record<string, { params: string[]; returnType: string }>;
}

/**
 * Generate a TypeScript file with typed function stubs from a manifest.
 *
 * Output includes:
 * - Type definitions for each discovered function
 * - A typed `createTransit()` factory function
 * - Per-language handle types with typed function signatures
 *
 * @param manifest - The scanner manifest
 * @param options - Generation options
 * @returns The generated TypeScript source code
 */
export function generateTypeScript(
  manifest: Manifest,
  options: TypeScriptGenOptions = {}
): string {
  const {
    outputPath = "transit.gen.ts",
    generateImports = true,
    generateSetup = true,
    typeOverrides = {},
  } = options;

  const lines: string[] = [];

  // Header
  lines.push("// AUTO-GENERATED by @sabeeirsharrma/codegen — do not edit");
  lines.push(`// Generated at: ${new Date(manifest.generatedAt).toISOString()}`);
  lines.push("");

  // Imports
  if (generateImports) {
    lines.push('import { transit } from "@sabeeirsharrma/transit";');
    lines.push("");
  }

  // Group entries by language
  const byLanguage = groupByLanguage(manifest.entries);

  // Generate per-language types
  for (const [lang, entries] of Object.entries(byLanguage)) {
    const typeName = capitalize(lang) + "Functions";
    const funcs = entries
      .filter((e) => !isInternalFunction(e.functionName))
      .map((e) => generateFunctionType(e, typeOverrides[e.functionName]));

    if (funcs.length === 0) continue;

    lines.push(`// ─── ${capitalize(lang)} functions ──────────────────────────────────────────`);
    lines.push("");
    lines.push(`export interface ${typeName} {`);

    for (const func of funcs) {
      lines.push(`  ${func}`);
    }

    lines.push("}");
    lines.push("");
  }

  // Generate combined types
  const allLangs = Object.keys(byLanguage);
  if (allLangs.length > 0) {
    const allTypeNames = allLangs.map((l) => capitalize(l) + "Functions");
    lines.push("// ─── Combined types ──────────────────────────────────────────────────────");
    lines.push("");
    lines.push("export interface TransitHandles {");
    for (const [lang, entries] of Object.entries(byLanguage)) {
      const publicCount = entries.filter((e) => !isInternalFunction(e.functionName)).length;
      if (publicCount > 0) {
        lines.push(`  ${lang}: ${capitalize(lang)}Functions;`);
      }
    }
    lines.push("}");
    lines.push("");
  }

  // Generate setup function
  if (generateSetup) {
    lines.push("// ─── Setup ────────────────────────────────────────────────────────────────");
    lines.push("");
    lines.push("/**");
    lines.push(" * Create a typed Transit instance.");
    lines.push(" * Call this once at application startup.");
    lines.push(" */");
    lines.push("export function createTransit(dirs: {");
    for (const lang of allLangs) {
      lines.push(`  ${lang}?: string;`);
    }
    lines.push("}) {");

    for (const lang of allLangs) {
      const fn = lang;
      lines.push(`  const ${fn}Handle = dirs.${lang} ? transit.${fn}(dirs.${lang}!) : null;`);
    }

    lines.push("");
    lines.push("  return {");
    for (const lang of allLangs) {
      lines.push(`    ${lang}: ${lang}Handle as ${capitalize(lang)}Functions,`);
    }
    lines.push("  };");
    lines.push("}");
    lines.push("");
  }

  return lines.join("\n");
}

// ─── Java glue generation ──────────────────────────────────────────────────

export interface JavaGlueOptions {
  /** Package name (default: "transit.java") */
  packageName?: string;
  /** Class name (default: "TransitService") */
  className?: string;
}

/**
 * Generate a Java TransitService.java with function registrations.
 *
 * The generated file registers all discovered functions with the Transit server.
 *
 * @param manifest - The scanner manifest
 * @param options - Generation options
 * @returns The generated Java source code
 */
export function generateJavaGlue(
  manifest: Manifest,
  options: JavaGlueOptions = {}
): string {
  const {
    packageName = "transit.java",
    className = "TransitService",
  } = options;

  const javaEntries = manifest.entries.filter(
    (e) => e.language === "java" && !isInternalFunction(e.functionName)
  );

  const lines: string[] = [];

  // Header
  lines.push("// AUTO-GENERATED by @sabeeirsharrma/codegen — do not edit");
  lines.push(`// Generated at: ${new Date(manifest.generatedAt).toISOString()}`);
  lines.push("");
  lines.push(`package ${packageName};`);
  lines.push("");
  lines.push("public class " + className + " {");

  // Function stubs
  for (const entry of javaEntries) {
    const methodName = entry.functionName;
    lines.push("");
    lines.push(`    /**`);
    lines.push(`     * Transit-exported function (Tier ${entry.exportTier})`);
    lines.push(`     * Source: ${entry.sourceFile}`);
    lines.push(`     * Signature: ${entry.signature}`);
    lines.push(`     */`);
    lines.push(`    public String ${methodName}(String argsJson) {`);
    lines.push(`        // TODO: Implement this function`);
    lines.push(`        return "{\"error\": \"not implemented\"}";`);
    lines.push(`    }`);
  }

  // Main method with registrations
  lines.push("");
  lines.push("    public static void main(String[] args) throws Exception {");
  lines.push("        TransitServer server = new TransitServer();");
  lines.push("        " + className + " service = new " + className + "();");
  lines.push("");

  for (const entry of javaEntries) {
    lines.push(
      `        server.registerFunction("${entry.functionName}", service::${entry.functionName});`
    );
  }

  lines.push("");
  lines.push("        server.start();");
  lines.push("    }");
  lines.push("}");

  return lines.join("\n");
}

// ─── Python glue generation ────────────────────────────────────────────────

export interface PythonGlueOptions {
  /** Module name (default: "transit_service") */
  moduleName?: string;
}

/**
 * Generate a Python transit_service.py with function registrations.
 *
 * @param manifest - The scanner manifest
 * @param options - Generation options
 * @returns The generated Python source code
 */
export function generatePythonGlue(
  manifest: Manifest,
  options: PythonGlueOptions = {}
): string {
  const {
    moduleName = "transit_service",
  } = options;

  const pyEntries = manifest.entries.filter(
    (e) => e.language === "python" && !isInternalFunction(e.functionName)
  );

  const lines: string[] = [];

  // Header
  lines.push('"""');
  lines.push("AUTO-GENERATED by @sabeeirsharrma/codegen — do not edit");
  lines.push(`Generated at: ${new Date(manifest.generatedAt).toISOString()}`);
  lines.push('"""');
  lines.push("");
  lines.push("import json");
  lines.push("from transit_server import TransitServer, register_function");
  lines.push("");

  // Function stubs
  for (const entry of pyEntries) {
    const funcName = entry.functionName;
    lines.push("");
    lines.push(`def ${funcName}(args_json):`);
    lines.push(`    """Transit-exported function (Tier ${entry.exportTier})`);
    lines.push(`    Source: ${entry.sourceFile}`);
    lines.push(`    Signature: ${entry.signature}`);
    lines.push('    """');
    lines.push(`    args = json.loads(args_json)`);
    lines.push(`    # TODO: Implement this function`);
    lines.push(`    return json.dumps({"error": "not implemented"})`);
  }

  // Main block
  lines.push("");
  lines.push("");
  lines.push('if __name__ == "__main__":');
  lines.push("    server = TransitServer()");
  lines.push("");

  for (const entry of pyEntries) {
    const funcName = entry.functionName;
    // Python server registers with camelCase
    const camelName = funcName.replace(/_([a-z])/g, (_: string, c: string) => c.toUpperCase());
    lines.push(
      `    register_function("${camelName}", ${funcName})`
    );
  }

  lines.push("");
  lines.push("    server.start()");

  return lines.join("\n");
}

// ─── C glue generation ────────────────────────────────────────────────────

export interface CGlueOptions {
  /** Header guard name (default: "TRANSIT_C_GLUE_H") */
  headerGuard?: string;
}

/**
 * Generate a C header file with N-API function registrations.
 *
 * @param manifest - The scanner manifest
 * @param options - Generation options
 * @returns The generated C source code
 */
export function generateCGlue(
  manifest: Manifest,
  options: CGlueOptions = {}
): string {
  const {
    headerGuard = "TRANSIT_C_GLUE_H",
  } = options;

  const cEntries = manifest.entries.filter(
    (e) => e.language === "c" && !isInternalFunction(e.functionName)
  );

  const lines: string[] = [];

  // Header
  lines.push("// AUTO-GENERATED by @sabeeirsharrma/codegen — do not edit");
  lines.push(`// Generated at: ${new Date(manifest.generatedAt).toISOString()}`);
  lines.push("");
  lines.push(`#ifndef ${headerGuard}`);
  lines.push(`#define ${headerGuard}`);
  lines.push("");
  lines.push("#include <node_api.h>");
  lines.push("");

  // Function declarations
  for (const entry of cEntries) {
    lines.push(`napi_value ${entry.functionName}_wrapper(napi_env env, napi_callback_info info);`);
  }

  lines.push("");
  lines.push("static void register_functions(napi_env env, napi_value exports) {");
  lines.push("    napi_value fn;");

  for (const entry of cEntries) {
    lines.push(`    napi_create_function(env, "${entry.functionName}", NAPI_AUTO_LENGTH, ${entry.functionName}_wrapper, NULL, &fn);`);
    lines.push(`    napi_set_named_property(env, exports, "${entry.functionName}", fn);`);
  }

  lines.push("}");
  lines.push("");
  lines.push("static napi_value init(napi_env env, napi_value exports) {");
  lines.push("    register_functions(env, exports);");
  lines.push("    return exports;");
  lines.push("}");
  lines.push("");
  lines.push("NAPI_MODULE(NODE_GYP_MODULE_NAME, init)");
  lines.push("");
  lines.push(`#endif // ${headerGuard}`);

  return lines.join("\n");
}

// ─── C++ glue generation ──────────────────────────────────────────────────

export interface CppGlueOptions {
  /** Header guard name (default: "TRANSIT_CPP_GLUE_H") */
  headerGuard?: string;
}

/**
 * Generate a C++ header file with N-API function registrations.
 *
 * @param manifest - The scanner manifest
 * @param options - Generation options
 * @returns The generated C++ source code
 */
export function generateCppGlue(
  manifest: Manifest,
  options: CppGlueOptions = {}
): string {
  const {
    headerGuard = "TRANSIT_CPP_GLUE_H",
  } = options;

  const cppEntries = manifest.entries.filter(
    (e) => e.language === "cpp" && !isInternalFunction(e.functionName)
  );

  const lines: string[] = [];

  // Header
  lines.push("// AUTO-GENERATED by @sabeeirsharrma/codegen — do not edit");
  lines.push(`// Generated at: ${new Date(manifest.generatedAt).toISOString()}`);
  lines.push("");
  lines.push(`#ifndef ${headerGuard}`);
  lines.push(`#define ${headerGuard}`);
  lines.push("");
  lines.push("#include <napi.h>");
  lines.push("");

  // Function declarations
  for (const entry of cppEntries) {
    lines.push(`Napi::Value ${entry.functionName}_wrapper(const Napi::CallbackInfo& info);`);
  }

  lines.push("");
  lines.push("Napi::Object Init(Napi::Env env, Napi::Object exports) {");

  for (const entry of cppEntries) {
    lines.push(`    exports.Set("${entry.functionName}", Napi::Function::New(env, ${entry.functionName}_wrapper));`);
  }

  lines.push("    return exports;");
  lines.push("}");
  lines.push("");
  lines.push("NODE_API_MODULE(addon, Init)");
  lines.push("");
  lines.push(`#endif // ${headerGuard}`);

  return lines.join("\n");
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function groupByLanguage(entries: ManifestEntry[]): Record<string, ManifestEntry[]> {
  const grouped: Record<string, ManifestEntry[]> = {};
  for (const entry of entries) {
    if (!grouped[entry.language]) {
      grouped[entry.language] = [];
    }
    grouped[entry.language].push(entry);
  }
  return grouped;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

/** Skip internal/utility functions like main, encodeCallRequest, etc. */
function isInternalFunction(name: string): boolean {
  const internal = new Set([
    "main", "encodeCallRequest", "encodeHealthPing",
    "decodeHeader", "readPayload", "decodeCallRequest",
    "MessageHeader", "CallRequest", "register_function",
    "start_server", "registerFunction", "getPort", "start", "stop",
    "TransitServer.start", "TransitServer.stop",
    "version", "parseSchema",
    "scan_directory", "scan_file_path", "invalidate_cache", "clear_cache",
  ]);
  return internal.has(name);
}

/**
 * Generate a TypeScript function signature from a manifest entry.
 *
 * Since the scanner produces string signatures, we generate `unknown` types
 * for parameters and `Promise<unknown>` for return types. Users can override
 * with specific types via typeOverrides.
 */
function generateFunctionType(
  entry: ManifestEntry,
  override?: { params: string[]; returnType: string }
): string {
  const name = entry.functionName;

  if (override) {
    const params = override.params.join(", ");
    return `${name}(${params}): Promise<${override.returnType}>;`;
  }

  // Default: single argsJson parameter, returns Promise<unknown>
  return `${name}(args: unknown): Promise<unknown>;`;
}
